### ISSUE TITLE
Day-8 things to learn

### ISSUE THREAD

**Issue by drgndenis** [drgndenis/one_hundred_days_of_code#3]
**Temelden Zirveye Flutter #7, #8, #9 in HardwareAndro Channel**

- [x] Navigation (#7)
- [x] Navigation's Details (#7)
- [ ] Tab & BottomAppBar (#8)
- [ ] Initialize & Model etc. (#8)
- [ ] What is service? (#9)
- [ ] Json (#9)
- [ ] Service structure (#9)
- [ ] Postman (#9)
- [ ] ServiceLearn,Dio, Get(Read), etc. (#9)
- [ ] Post(Create) (#9)
- [ ] PostService Class (#9)
- [ ] Try Catch (#9)
- [ ] Updated (#9)
- [ ] Delete, etc. (#9)
